resolver: lts-16.18
packages:
  - katip
  - katip-elasticsearch
  - katip-datadog
  - katip-logzio
extra-deps:
  - ../bloodhound
  - unliftio-core-0.2.0.1
  - resourcet-1.2.3
flags:
  katip:
    lib-Werror: true
  katip-elasticsearch:
    lib-Werror: true
  katip-datadog:
    lib-Werror: true
  katip-logzio:
    lib-Werror: true
